/**
 * Push CI/CD Workflow - Creates GitHub Actions workflow directly via GitHub API
 */
import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';

// GitHub Actions workflow template
const WORKFLOW_TEMPLATE = `# HackJudge CI/CD Workflow
# Auto-generated by HackJudge AI

name: HackJudge CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint --if-present

    - name: Run tests
      run: npm test --if-present

    - name: Build
      run: npm run build --if-present

    - name: Security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
`;

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { owner, repo, branch = 'main' } = body;

        if (!owner || !repo) {
            return NextResponse.json(
                { success: false, error: 'Missing required fields: owner, repo' },
                { status: 400 }
            );
        }

        // Get GitHub token from cookies
        const cookieStore = await cookies();
        const token = cookieStore.get('github_token')?.value;

        if (!token) {
            return NextResponse.json(
                { success: false, error: 'Not authenticated. Please sign in with GitHub.' },
                { status: 401 }
            );
        }

        // Create workflow file via GitHub API
        const path = '.github/workflows/hackjudge-ci.yml';
        const content = Buffer.from(WORKFLOW_TEMPLATE).toString('base64');

        // First, check if file exists (to get SHA for update)
        let sha: string | undefined;
        try {
            const existingFile = await fetch(
                `https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${branch}`,
                {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Accept': 'application/vnd.github+json',
                    },
                }
            );
            if (existingFile.ok) {
                const data = await existingFile.json();
                sha = data.sha;
            }
        } catch {
            // File doesn't exist, that's fine
        }

        // Create or update the file
        const response = await fetch(
            `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
            {
                method: 'PUT',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Accept': 'application/vnd.github+json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    message: '🚀 Add HackJudge CI/CD workflow',
                    content,
                    branch,
                    ...(sha ? { sha } : {}),
                }),
            }
        );

        if (!response.ok) {
            const error = await response.json();
            return NextResponse.json(
                { success: false, error: error.message || 'Failed to create workflow' },
                { status: response.status }
            );
        }

        const result = await response.json();

        return NextResponse.json({
            success: true,
            message: 'CI/CD workflow created successfully',
            file: {
                path: result.content?.path,
                url: result.content?.html_url,
            },
            commit: {
                sha: result.commit?.sha,
                url: result.commit?.html_url,
            },
        });
    } catch (error) {
        console.error('Push workflow error:', error);
        return NextResponse.json(
            { success: false, error: 'Internal server error' },
            { status: 500 }
        );
    }
}
